import Image from 'next/image'
import Link from 'next/link'
import type { Metadata } from 'next'
import { isOpenAccess } from '@/config/access'
import { absoluteSiteUrl, withBasePath } from '@/config/paths'
import { siteConfig } from '@/config/site'
import { breadcrumbListJsonLd } from '@/lib/breadcrumbs'
import { dogfoodOgImageUrl, ogImageWithAlt } from '@/lib/dogfood-og'
import { clipMetaDescription } from '@/lib/seo-meta'
import { Button } from '@/components/ui/button'
import { HeroLiveDemo } from '@/components/marketing/hero-live-demo'
import { OgkitLlmFacts } from '@/components/seo/LlmFacts'
import {
  OGKIT_AI_CATEGORY,
  OGKIT_AI_DESCRIPTION,
  withAiMetadata,
} from '@/lib/llm-meta'

const openAccess = isOpenAccess()
const homeCanonical = absoluteSiteUrl('')
const homeTitle = `${siteConfig.name} — Open Graph image API for 1200×630 social cards`
const homeDescription = clipMetaDescription(
  openAccess
    ? 'Free Open Graph image API: 1200×630 PNG social cards from one HTTPS URL. Templates, Playground, Next.js metadata — no watermark during open access.'
    : siteConfig.description,
)
const homeOgImage = dogfoodOgImageUrl({
  title: 'OGKit',
  subtitle: 'Open Graph image API',
  template: 'brand',
})
const homeOgAlt = 'OGKit dynamic Open Graph image API — 1200×630 social cards'

export const metadata: Metadata = withAiMetadata(
  {
    title: { absolute: homeTitle },
    description: homeDescription,
    alternates: { canonical: homeCanonical },
    openGraph: {
      type: 'website',
      url: homeCanonical,
      siteName: siteConfig.name,
      title: homeTitle,
      description: homeDescription,
      images: ogImageWithAlt(homeOgImage, homeOgAlt),
    },
    twitter: {
      card: 'summary_large_image',
      title: homeTitle,
      description: homeDescription,
      images: [homeOgImage],
    },
  },
  {
    aiDescription: OGKIT_AI_DESCRIPTION,
    aiCategory: OGKIT_AI_CATEGORY,
  },
)

export default function HomePage() {
  const faq = [
    {
      question: 'What is OGKit?',
      answer:
        'OGKit is an Open Graph image API that returns dynamic 1200×630 PNG social preview images from a template slug and query parameters.',
    },
    {
      question: openAccess ? 'Is OGKit free right now?' : 'Why crypto-only checkout?',
      answer: openAccess
        ? 'Yes. Open access means no watermark and no quota for everyone. Use demo=1 without an account, or sign in for an API key.'
        : 'Crypto checkout keeps OGKit available to global developers without card processors, regional billing blocks, or subscription lock-in.',
    },
    {
      question: 'Is OGKit a Vercel OG alternative?',
      answer:
        'Yes. OGKit is a Vercel OG alternative for teams that want hosted templates, API keys, and a Playground instead of maintaining custom @vercel/og routes.',
    },
    {
      question: 'Does OGKit work with Next.js?',
      answer:
        'Yes. In Next.js App Router, point metadata.openGraph.images and twitter.images at a full OGKit image URL generated on the server.',
    },
    {
      question: 'How is OGKit different from screenshot APIs?',
      answer:
        'Screenshot APIs capture webpages. OGKit generates purpose-built Open Graph cards from structured fields like title, author, image, logo, and product details.',
    },
  ]

  const previewTemplates = [
    ['Article', '/previews/article-preview.png', 'Article social preview image generated by OGKit'],
    ['Product', '/previews/product-preview.png', 'Product social preview image generated by OGKit'],
    ['Code', '/previews/code-preview.png', 'Developer code social preview image generated by OGKit'],
  ] as const

  const useCases = [
    ['Next.js OG images', '/for/nextjs'],
    ['Dynamic social preview images', '/use-case/dynamic-social-preview-images'],
    ['Signed URLs guide', '/guides/signed-urls'],
    ['Auto OG from URL', '/guides/auto-og'],
    ['Caching & rescrape', '/guides/caching-and-rescrape'],
    ['MCP for Cursor', '/guides/mcp'],
    ['Open Graph SEO guide', '/blog/open-graph-images-seo-guide'],
    ['Product launch images', '/use-case/product-launch'],
  ] as const

  const comparisons = [
    ['OGKit vs Vercel OG', '/compare/ogkit-vs-vercel-og'],
    ['OGKit vs Bannerbear', '/compare/ogkit-vs-bannerbear'],
    ['OGKit vs Placid', '/compare/ogkit-vs-placid'],
    ['OGKit vs screenshot APIs', '/compare/ogkit-vs-screenshot-apis'],
  ] as const

  const siteRoot = absoluteSiteUrl('')
  const websiteJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: siteConfig.name,
    url: siteRoot,
    description: homeDescription,
    publisher: { '@type': 'Organization', name: siteConfig.name, url: siteRoot, sameAs: siteConfig.github },
    primaryImageOfPage: {
      '@type': 'ImageObject',
      url: absoluteSiteUrl('/og-image.jpg'),
      width: 1200,
      height: 630,
    },
  }
  const softwareJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: siteConfig.name,
    applicationCategory: 'DeveloperApplication',
    operatingSystem: 'Web',
    url: siteRoot,
    description: homeDescription,
    offers: openAccess
      ? [{ '@type': 'Offer', name: 'Open access', price: '0', priceCurrency: 'USD', url: absoluteSiteUrl('/pricing') }]
      : [
          { '@type': 'Offer', name: 'Free', price: '0', priceCurrency: 'USD', url: absoluteSiteUrl('/pricing') },
          { '@type': 'Offer', name: 'Pro', price: '19', priceCurrency: 'USD', url: absoluteSiteUrl('/pricing') },
          { '@type': 'Offer', name: 'Scale', price: '99', priceCurrency: 'USD', url: absoluteSiteUrl('/pricing') },
        ],
  }
  const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faq.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: { '@type': 'Answer', text: item.answer },
    })),
  }
  const breadcrumbLd = breadcrumbListJsonLd([])

  return (
    <div className="relative">
      <OgkitLlmFacts />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }} />

      <section className="relative overflow-hidden bg-surface-dark text-white">
        <div aria-hidden className="pointer-events-none absolute inset-0 hero-gradient" />

        <div className="relative mx-auto flex min-h-[64svh] max-w-6xl flex-col justify-end px-4 pb-10 pt-16 sm:min-h-[60svh] sm:px-6 sm:pb-12 sm:pt-20">
          <div className="max-w-3xl animate-fade-up">
            <p className="font-heading text-5xl font-bold tracking-tight sm:text-7xl md:text-8xl">
              <span className="gradient-text">{siteConfig.name}</span>
            </p>
            <h1 className="mt-4 max-w-2xl font-heading text-3xl font-semibold tracking-tight text-white sm:text-5xl">
              Social cards from one HTTPS URL
            </h1>
            <p className="mt-4 max-w-xl text-base leading-relaxed text-white/70 sm:text-lg">
              {openAccess
                ? 'Free 1200×630 Open Graph PNGs for Slack, LinkedIn, Discord, and X — no watermark, no quota.'
                : 'Turn title, subtitle, and logo into a 1200×630 og:image for any framework — no Satori route to maintain.'}
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Button
                asChild
                size="lg"
                className="rounded-full bg-brand px-7 font-semibold text-white hover:bg-brand-light"
              >
                <Link href={withBasePath('/playground')}>Try playground</Link>
              </Button>
              <Button
                asChild
                size="lg"
                variant="outline"
                className="rounded-full border-white/25 bg-transparent px-7 text-white hover:bg-white/10 hover:text-white"
              >
                <Link href={withBasePath('/login')}>Get API key</Link>
              </Button>
            </div>
          </div>
        </div>

        <div className="relative border-t border-white/10">
          <HeroLiveDemo />
        </div>
      </section>

      <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6 sm:py-24">
        <section className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-start">
          <div>
            <h2 className="font-heading text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl">
              One URL in. PNG out.
            </h2>
            <p className="mt-4 max-w-md leading-relaxed text-gray-600">
              Build the image URL on the server, put it in{' '}
              <code className="rounded-md bg-gray-100 px-1.5 py-0.5 font-mono text-xs text-gray-900">og:image</code>, and
              let social scrapers cache the same bytes forever.
            </p>
          </div>
          <ol className="space-y-8 border-l border-gray-200 pl-6">
            {[
              ['Pick a template', 'article, product, minimal, gradient, brand, dark-code, and more.'],
              ['Pass fields as query params', 'title, subtitle, author, logo, price, accent — URL-encoded.'],
              ['Drop the HTTPS URL into metadata', 'Works with Next.js, Astro, Rails, Django, Hugo, static HTML.'],
            ].map(([step, copy], i) => (
              <li key={step} className="relative">
                <span className="absolute -left-[1.9rem] top-0 flex h-5 w-5 -translate-x-1/2 items-center justify-center rounded-full bg-brand font-heading text-[10px] font-bold text-white">
                  {i + 1}
                </span>
                <p className="font-heading text-lg font-semibold tracking-tight text-gray-900">{step}</p>
                <p className="mt-1 text-sm text-gray-600">{copy}</p>
              </li>
            ))}
          </ol>
        </section>

        <section className="mt-24">
          <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end">
            <div>
              <h2 className="font-heading text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl">
                Templates that ship
              </h2>
              <p className="mt-2 max-w-xl text-sm text-gray-600">
                Real 1200×630 cards for articles, products, and developer docs.
              </p>
            </div>
            <Link
              href={withBasePath('/docs')}
              className="text-sm font-semibold text-brand underline-offset-4 hover:underline"
            >
              Full API reference
            </Link>
          </div>
          <div className="mt-8 grid gap-4 sm:grid-cols-3">
            {previewTemplates.map(([label, src, alt]) => (
              <figure key={src} className="group overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm">
                <Image
                  src={src}
                  width={1200}
                  height={630}
                  alt={alt}
                  loading="lazy"
                  sizes="(min-width: 1024px) 350px, 100vw"
                  className="aspect-[1200/630] w-full object-cover transition duration-500 group-hover:scale-[1.02]"
                />
                <figcaption className="px-4 py-3 text-xs font-semibold uppercase tracking-wider text-gray-500">
                  {label}
                </figcaption>
              </figure>
            ))}
          </div>
        </section>

        <section className="mt-24 grid gap-10 border-y border-gray-100 py-16 sm:grid-cols-3">
          {[
            [
              'For AI-built sites',
              'Paste docs into Cursor, generate deterministic OG URLs, keep secrets server-side.',
            ],
            [
              openAccess ? 'Free while open' : 'For indie teams',
              openAccess
                ? 'No watermark and no quota right now. Sign in when you want rotatable API keys.'
                : 'Start with demo previews, then upgrade when you need production quota.',
            ],
            [
              'For production',
              'Signed URLs, domain allowlists, cache-friendly PNGs, and a Playground to test every template.',
            ],
          ].map(([title, copy]) => (
            <div key={title}>
              <h2 className="font-heading text-xl font-semibold tracking-tight text-gray-900">{title}</h2>
              <p className="mt-2 text-sm leading-relaxed text-gray-600">{copy}</p>
            </div>
          ))}
        </section>

        <section className="relative mt-24 overflow-hidden rounded-3xl bg-surface-dark px-6 py-12 text-white sm:px-10">
          <div aria-hidden className="pointer-events-none absolute inset-0 hero-gradient opacity-60" />
          <div className="relative">
          <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-brand-light">Request shape</p>
          <h2 className="mt-3 font-heading text-3xl font-semibold tracking-tight">How the API looks</h2>
          <div className="mt-8 grid gap-3 font-mono text-xs sm:grid-cols-3">
            {[
              ['GET', '/api/og/article?title=Ship%20notes', '200 image/png'],
              ['Cache', 'public, s-maxage=31536000', 'CDN ready'],
              ['Use', 'metadata.openGraph.images', 'Next.js'],
            ].map(([label, value, status]) => (
              <div key={value} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                <div className="flex items-center justify-between gap-3 text-white/45">
                  <span>{label}</span>
                  <span className="text-brand-light">{status}</span>
                </div>
                <p className="mt-3 break-all text-sm text-white">{value}</p>
              </div>
            ))}
          </div>
          <p className="mt-6 max-w-2xl text-sm leading-relaxed text-white/60">
            MCP for Cursor: <code className="text-brand-light">{siteConfig.url}/api/mcp</code>. Read the{' '}
            <Link className="text-white underline underline-offset-4" href={withBasePath('/blog/open-graph-images-seo-guide')}>
              Open Graph SEO guide
            </Link>{' '}
            for caching and rescrape patterns.
          </p>
          </div>
        </section>

        <section className="mt-24 grid gap-14 lg:grid-cols-2">
          <div>
            <h2 className="font-heading text-3xl font-semibold tracking-tight text-gray-900">Use cases</h2>
            <ul className="mt-6 space-y-3">
              {useCases.map(([label, href]) => (
                <li key={href}>
                  <Link
                    href={withBasePath(href)}
                    className="group flex items-center justify-between border-b border-gray-100 py-3 text-sm font-medium text-gray-800 transition hover:text-brand"
                  >
                    <span>{label}</span>
                    <span className="text-gray-400 transition group-hover:translate-x-0.5 group-hover:text-brand">→</span>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <h2 className="font-heading text-3xl font-semibold tracking-tight text-gray-900">Compare</h2>
            <ul className="mt-6 space-y-3">
              {comparisons.map(([label, href]) => (
                <li key={href}>
                  <Link
                    href={withBasePath(href)}
                    className="group flex items-center justify-between border-b border-gray-100 py-3 text-sm font-medium text-gray-800 transition hover:text-brand"
                  >
                    <span>{label}</span>
                    <span className="text-gray-400 transition group-hover:translate-x-0.5 group-hover:text-brand">→</span>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section className="mt-24">
          <h2 className="font-heading text-3xl font-semibold tracking-tight text-gray-900">FAQ</h2>
          <div className="mt-8 grid gap-8 sm:grid-cols-2">
            {faq.map((item) => (
              <div key={item.question}>
                <h3 className="font-heading text-lg font-semibold tracking-tight text-gray-900">{item.question}</h3>
                <p className="mt-2 text-sm leading-relaxed text-gray-600">{item.answer}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-24 border-t border-gray-100 pt-12">
          <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-gray-400">Also from webmorp.art</p>
          <div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <h2 className="font-heading text-2xl font-semibold tracking-tight text-gray-900">
                Business card websites — $100
              </h2>
              <p className="mt-2 max-w-lg text-sm text-gray-600">
                One-page sites live in 24 hours. Examples: pveselov.space, uniprep2go.study.
              </p>
            </div>
            <Button asChild variant="outline" className="rounded-full border-brand text-brand hover:bg-brand hover:text-white">
              <Link href="/">Get a website →</Link>
            </Button>
          </div>
        </section>
      </div>
    </div>
  )
}
