import Image from 'next/image'
import Link from 'next/link'
import type { Metadata } from 'next'
import { absoluteSiteUrl, withBasePath } from '@/config/paths'
import { siteConfig } from '@/config/site'
import { breadcrumbListJsonLd } from '@/lib/breadcrumbs'
import { clipMetaDescription } from '@/lib/seo-meta'
import { Button } from '@/components/ui/button'
import { HeroLiveDemo } from '@/components/marketing/hero-live-demo'

const homeCanonical = absoluteSiteUrl('')
/** ~54 chars: avoids root `title.template` appending `| OGKit` twice in SERP. */
const homeTitle = `${siteConfig.name} — Open Graph image API for 1200×630 social cards`
const homeDescription = clipMetaDescription(siteConfig.description)
export const metadata: Metadata = {
  title: { absolute: homeTitle },
  description: homeDescription,
  alternates: { canonical: homeCanonical },
  openGraph: {
    type: 'website',
    url: homeCanonical,
    siteName: siteConfig.name,
    title: homeTitle,
    description: homeDescription,
    images: [{ url: '/og-image.jpg', width: 1200, height: 630, alt: 'OGKit dynamic Open Graph image API' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: homeTitle,
    description: homeDescription,
    images: ['/og-image.jpg'],
  },
}

export default function HomePage() {
  const faq = [
    {
      question: 'What is OGKit?',
      answer:
        'OGKit is a crypto-native Open Graph image API that returns dynamic 1200x630 PNG social preview images from template and query parameters.',
    },
    {
      question: 'Why crypto-only checkout?',
      answer:
        'Crypto checkout keeps OGKit available to global developers without card processors, regional billing blocks, or subscription lock-in.',
    },
    {
      question: 'Is OGKit a Vercel OG alternative?',
      answer:
        'Yes. OGKit is a Vercel OG alternative for teams that want hosted templates, API keys, quotas, and a Playground instead of maintaining custom @vercel/og routes.',
    },
    {
      question: 'Does OGKit work with Next.js?',
      answer:
        'Yes. In Next.js App Router, point metadata.openGraph.images and twitter.images at a full OGKit image URL generated on the server.',
    },
    {
      question: 'How is OGKit different from screenshot APIs?',
      answer:
        'Screenshot APIs capture webpages. OGKit generates purpose-built Open Graph cards from structured fields like title, author, image, logo, and product details.',
    },
  ]
  const heroBadges = ['Live demo on homepage', 'No-login previews', 'Cursor MCP', 'Auto API key on sign-in']
  const previewTemplates = [
    ['Article template', '/previews/article-preview.png', 'Article social preview image generated by OGKit'],
    ['Product template', '/previews/product-preview.png', 'Product social preview image generated by OGKit'],
    ['Code template', '/previews/code-preview.png', 'Developer code social preview image generated by OGKit'],
  ] as const
  const workflowCards = [
    [
      'Try first',
      'Generate watermarked demo images without creating an account or entering a card.',
      'demo=1',
      'from-cyan-400 to-blue-600',
    ],
    [
      'Pay globally',
      'Crypto checkout avoids card processor limits and keeps paid access simple for international builders.',
      'USDT',
      'from-emerald-300 to-teal-600',
    ],
    [
      'Ship safely',
      'Use signed URLs and domain allowlists when public pages need controlled image generation.',
      'HMAC',
      'from-orange-300 to-rose-500',
    ],
  ] as const
  const useCases = [
    ['Next.js OG images', '/for/nextjs'],
    ['Dynamic social preview images', '/use-case/dynamic-social-preview-images'],
    ['Blog post social cards', '/use-case/blog'],
    ['Changelog previews', '/use-case/changelog'],
    ['Product launch images', '/use-case/product-launch'],
    ['Vercel deployment', '/platform/vercel'],
    ['API documentation', '/docs'],
    ['Open Graph SEO guide', '/blog/open-graph-images-seo-guide'],
  ] as const
  const comparisons = [
    ['OGKit vs Vercel OG', '/compare/ogkit-vs-vercel-og'],
    ['OGKit vs MetaShot', '/compare/ogkit-vs-metashot'],
    ['OGKit vs OGMagic', '/compare/ogkit-vs-ogmagic'],
    ['OGKit vs Bannerbear', '/compare/ogkit-vs-bannerbear'],
    ['OGKit vs Placid', '/compare/ogkit-vs-placid'],
    ['OGKit vs screenshot APIs', '/compare/ogkit-vs-screenshot-apis'],
    ['Satori vs Puppeteer', '/compare/satori-vs-puppeteer'],
  ] as const

  const siteRoot = absoluteSiteUrl('')
  const websiteJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: siteConfig.name,
    url: siteRoot,
    description: siteConfig.description,
    publisher: { '@type': 'Organization', name: siteConfig.name, url: siteRoot, sameAs: siteConfig.github },
    primaryImageOfPage: {
      '@type': 'ImageObject',
      url: absoluteSiteUrl('/og-image.jpg'),
      width: 1200,
      height: 630,
    },
  }
  const softwareJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: siteConfig.name,
    applicationCategory: 'DeveloperApplication',
    operatingSystem: 'Web',
    url: siteRoot,
    description: siteConfig.description,
    offers: [
      { '@type': 'Offer', name: 'Free', price: '0', priceCurrency: 'USD', url: absoluteSiteUrl('/pricing') },
      { '@type': 'Offer', name: 'Pro', price: '19', priceCurrency: 'USD', url: absoluteSiteUrl('/pricing') },
      { '@type': 'Offer', name: 'Scale', price: '99', priceCurrency: 'USD', url: absoluteSiteUrl('/pricing') },
    ],
  }
  const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faq.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: item.answer,
      },
    })),
  }
  const breadcrumbLd = breadcrumbListJsonLd([])

  return (
    <div className="relative overflow-hidden">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }} />
      <div className="absolute left-1/2 top-0 -z-10 h-[42rem] w-[90rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle_at_35%_20%,rgba(56,189,248,0.24),transparent_32%),radial-gradient(circle_at_70%_35%,rgba(99,102,241,0.18),transparent_28%),linear-gradient(180deg,rgba(248,250,252,0.95),rgba(255,255,255,0))]" />
      <div className="absolute right-0 top-72 -z-10 h-72 w-72 rounded-full bg-cyan-200/30 blur-3xl" />

      <main className="container max-w-6xl py-16 sm:py-20">
        <section className="mb-10 rounded-2xl border border-indigo-200/80 bg-gradient-to-r from-indigo-950 via-slate-900 to-violet-950 px-5 py-4 text-white shadow-lg sm:flex sm:items-center sm:justify-between sm:gap-6 sm:px-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-300">Also from webmorp.art</p>
            <p className="mt-1 text-base font-semibold sm:text-lg">
              Business card websites — $100 flat, live in 24 hours
            </p>
            <p className="mt-1 text-sm text-slate-300">
              Your texts and design if you have them — otherwise we write and design the site. Examples: pveselov.space, uniprep2go.study.
            </p>
          </div>
          <Button asChild size="sm" variant="secondary" className="mt-4 shrink-0 bg-white text-slate-900 hover:bg-slate-100 sm:mt-0">
            <Link href="/">Get your website →</Link>
          </Button>
        </section>

        <section className="grid items-center gap-10 lg:grid-cols-[0.9fr_1.1fr]">
          <div>
            <p className="inline-flex rounded-full border border-slate-200 bg-white/70 px-3 py-1 text-sm font-medium text-slate-600 shadow-sm backdrop-blur">
              {siteConfig.tagline}
            </p>
            <h1 className="mt-5 max-w-3xl text-5xl font-black tracking-[-0.055em] text-slate-950 sm:text-7xl">
              Open Graph image API for 1200×630 social cards
            </h1>
            <p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">
              {siteConfig.name} turns one HTTPS URL into a 1200×630 PNG{' '}
              <code className="rounded-md bg-slate-950 px-1.5 py-0.5 font-mono text-sm text-white">og:image</code> for
              any framework. Generate dynamic social preview cards for Slack, Discord, LinkedIn, iMessage, and X from
              server-rendered metadata — no custom renderer, no Satori bundle budget, no headless browser. Use OGKit as a
              hosted alternative to Vercel OG routes, screenshot services, and hand-designed cards; pay globally with
              crypto when you need production quota.
            </p>
            <div className="mt-6 flex flex-wrap gap-2 text-xs font-semibold text-slate-600">
              {heroBadges.map((item) => (
                <span key={item} className="rounded-full border border-slate-200 bg-white/75 px-3 py-1 shadow-sm">
                  {item}
                </span>
              ))}
            </div>
            <div className="mt-8 flex flex-wrap gap-4">
              <Button asChild size="lg" className="shadow-lg shadow-slate-950/15">
                <Link href={withBasePath('/playground')}>Try the OG image playground</Link>
              </Button>
              <Button asChild size="lg" variant="outline" className="bg-white/80">
                <Link href={withBasePath('/login')}>Sign in — auto API key</Link>
              </Button>
              <Button asChild size="lg" variant="outline" className="bg-white/80">
                <Link href={withBasePath('/docs')}>Read the API docs</Link>
              </Button>
            </div>
            <p className="mt-4 font-mono text-xs text-slate-500">
              Cursor: add MCP{' '}
              <code className="rounded bg-slate-100 px-1.5 py-0.5">{siteConfig.url}/api/mcp</code>
              {' · '}
              <a className="underline" href="https://cursor.com/marketplace/publish">
                Marketplace plugin
              </a>
            </p>
            <p className="mt-4 text-sm text-slate-500">
              New to Open Graph images?{' '}
              <Link href={withBasePath('/blog/open-graph-images-seo-guide')} className="font-semibold text-slate-800 underline underline-offset-2">
                Read the Open Graph image SEO guide 2026 →
              </Link>
            </p>
          </div>

          <HeroLiveDemo />
        </section>

        <section className="mt-24">
          <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end">
          <div>
            <h2 className="text-3xl font-black tracking-tight">Preview templates that look ready to ship</h2>
            <p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">
              OGKit generates real 1200x630 social cards for articles, products, launch pages, and developer docs.
            </p>
          </div>
          <Link href={withBasePath('/playground')} className="text-sm font-medium underline">
            Open Playground
          </Link>
        </div>
          <div className="mt-6 grid gap-5 md:grid-cols-3">
          {previewTemplates.map(([label, src, alt]) => (
            <figure
              key={src}
              className="group overflow-hidden rounded-2xl border bg-white shadow-xl shadow-slate-950/5 transition duration-300 hover:-translate-y-1 hover:shadow-2xl hover:shadow-slate-950/10"
            >
              <Image
                src={src}
                width={1200}
                height={630}
                alt={alt}
                loading="lazy"
                sizes="(min-width: 1024px) 350px, (min-width: 640px) 45vw, 100vw"
                className="aspect-[1200/630] object-cover transition duration-300 group-hover:scale-[1.03]"
              />
              <figcaption className="border-t bg-slate-50/80 px-4 py-3 text-sm font-semibold">{label}</figcaption>
            </figure>
          ))}
        </div>
      </section>

      <section className="mt-20 grid gap-4 md:grid-cols-3">
        {[
          ['For AI-assisted developers', 'Paste the docs into Cursor or Claude and build deterministic 1200x630 PNG URLs for Next.js, Astro, Rails, Django, and any stack.'],
          ['For global indie teams', 'Start with watermarked demo previews, then upgrade through crypto checkout when you need production quota and no watermark.'],
          ['For production', 'API keys, monthly quota, cache-friendly responses, signed URLs, domain allowlists, and a Playground for testing every template.'],
        ].map(([title, copy]) => (
          <div key={title} className="rounded-2xl border bg-white p-6 shadow-sm">
            <h2 className="text-lg font-bold">{title}</h2>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{copy}</p>
          </div>
        ))}
      </section>

      <section className="mt-20 grid gap-8 rounded-[2rem] border bg-slate-950 p-6 text-white shadow-2xl shadow-slate-950/15 lg:grid-cols-[0.9fr_1.1fr] lg:p-10">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.22em] text-cyan-300">One URL in, social card out</p>
          <h2 className="mt-3 text-3xl font-black tracking-tight">How the Open Graph image API works</h2>
          <p className="mt-4 text-sm leading-relaxed text-slate-300">
            Every OGKit template is an HTTPS endpoint. You pass structured fields — title, subtitle, author, logo,
            product image, price, or code snippet — as URL query parameters, and the API returns a ready-to-embed
            1200×630 PNG. There is nothing to install: build the URL on the server, assign it to{' '}
            <code className="rounded bg-white/10 px-1.5 py-0.5 font-mono text-white">openGraph.images</code> (Next.js),
            a <code className="rounded bg-white/10 px-1.5 py-0.5 font-mono text-white">&lt;meta property=&quot;og:image&quot;&gt;</code>{' '}
            tag, or any framework metadata layer, and you are done.
          </p>
          <p className="mt-4 text-sm leading-relaxed text-slate-300">
            Because image URLs are deterministic, CDNs and social-network scrapers cache the PNG after the first fetch.
            Slack, LinkedIn, iMessage, Discord, and X unfurl the same cached byte-for-byte preview on every reshare — no
            re-render, no rate-limit surprise. Watermarked{' '}
            <code className="rounded bg-white/10 px-1.5 py-0.5 font-mono text-white">demo=1</code> previews are available
            without an account, so you can validate your card layout in the{' '}
            <Link className="text-cyan-200 underline" href={withBasePath('/playground')}>
              Playground
            </Link>{' '}
            before committing to a production key. Read the{' '}
            <Link className="text-cyan-200 underline" href={withBasePath('/blog/open-graph-images-seo-guide')}>
              Open Graph SEO guide
            </Link>{' '}
            for a deeper walkthrough of metadata patterns, caching, and common mistakes.
          </p>
        </div>
        <div className="grid gap-3 self-center font-mono text-xs">
          {[
            ['GET', '/api/og/article?title=Ship%20notes', '200 image/png'],
            ['Cache', 'public, s-maxage=31536000', 'CDN ready'],
            ['Use', 'metadata.openGraph.images', 'Next.js'],
          ].map(([label, value, status]) => (
            <div key={value} className="rounded-2xl border border-white/10 bg-white/[0.06] p-4">
              <div className="flex items-center justify-between gap-4 text-slate-400">
                <span>{label}</span>
                <span className="rounded-full bg-emerald-400/15 px-2 py-1 text-emerald-200">{status}</span>
              </div>
              <p className="mt-3 break-all text-sm text-white">{value}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-20 space-y-4">
        <h2 className="text-3xl font-black tracking-tight">Built for crypto-native developer workflows</h2>
        <div className="grid gap-4 md:grid-cols-3">
          {workflowCards.map(([title, copy, chip, gradient]) => (
            <div key={title} className="overflow-hidden rounded-2xl border bg-white shadow-sm">
              <div className={`h-24 bg-gradient-to-br ${gradient} p-5 text-white`}>
                <span className="rounded-full bg-white/20 px-3 py-1 font-mono text-xs font-semibold">{chip}</span>
              </div>
              <div className="p-5">
              <h3 className="font-bold">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{copy}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-20 space-y-4">
        <h2 className="text-3xl font-black tracking-tight">Open Graph image API use cases</h2>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {useCases.map(([label, href]) => (
            <Link
              key={href}
              href={withBasePath(href)}
              className="rounded-2xl border bg-white p-4 text-sm font-semibold shadow-sm transition hover:-translate-y-0.5 hover:bg-slate-50"
            >
              {label}
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-20 space-y-4">
        <h2 className="text-3xl font-black tracking-tight">Compare OGKit</h2>
        <p className="max-w-3xl text-sm leading-relaxed text-muted-foreground">
          Short decision pages for teams evaluating OGKit against custom Vercel OG routes, MetaShot, OGMagic,
          Bannerbear-style template tools, and browser screenshot APIs.
        </p>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {comparisons.map(([label, href]) => (
            <Link
              key={href}
              href={withBasePath(href)}
              className="rounded-2xl border bg-white p-4 text-sm font-semibold shadow-sm transition hover:-translate-y-0.5 hover:bg-slate-50"
            >
              {label}
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-20 rounded-[2rem] border bg-white p-6 shadow-sm">
        <h2 className="text-3xl font-black tracking-tight">Frequently asked questions</h2>
        <div className="mt-4 grid gap-5 md:grid-cols-2">
          {faq.map((item) => (
            <div key={item.question}>
              <h3 className="font-bold">{item.question}</h3>
              <p className="mt-1 text-sm text-muted-foreground">{item.answer}</p>
            </div>
          ))}
        </div>
      </section>
      </main>
    </div>
  )
}
